---
version: '2.1'

services:
    integration-tests:
      environment:
        - http_proxy=
        - https_proxy=
        - no_proxy=
        - SMOKE_TEST_USERNAME=test1@test.com
        - SMOKE_TEST_PASSWORD=Password12
      volumes:
        - .:/usr/src/app
    remote-webdriver:
      image: docker.artifactory.reform.hmcts.net/selenium/standalone-chrome-debug:3.8.1
      ports:
        - 5900:5900
      environment:
        - http_proxy=
        - https_proxy=
        - no_proxy=
    citizen-frontend:
      ports:
        - 3000:3000
      environment:
        - http_proxy=
        - https_proxy=
        - no_proxy=
    legal-frontend:
      ports:
        - 4000:4000
    authentication-web:
      ports:
        - 8000:8000
    idam-api:
      environment:
        - http_proxy=
        - https_proxy=
        - no_proxy=
      ports:
        - 8080:8080
    claim-store-api:
      environment:
        - http_proxy=
        - https_proxy=
        - no_proxy=
      ports:
        - 4400:4400
      environment:
        - FRONTEND_BASE_URL=https://localhost:3000
    fees-api:
      ports:
        - 4182:8080
    draft-store-api:
      ports:
        - 8800:8800
    service-auth-provider-api:
      ports:
        - 4552:8080
    payments-api:
      environment:
        - http_proxy=
        - https_proxy=
        - no_proxy=
      ports:
       - 4421:8080
    pdf-service-api:
      ports:
        - 5500:5500
    shared-database:
      ports:
        - 5430:5432
      volumes:
        - shared-database-data:/var/lib/postgresql/data
    smtp-server:
      ports:
        - 1025:1025
        - 8025:8025
    document-management-api-gateway-web:
      ports:
        - 8085:8080
    document-management-api:
      ports:
        - 8083:8080
    ccd-definition-store-api:
      ports:
        - 4451:4451
    ccd-data-store-api:
      ports:
        - 4452:4452
    ccd-user-profile-api:
      ports:
        - 4453:4453
    ccd-importer:
      volumes:
        - ./docker/ccd-definition-import/data/CCD_Definition_CMC.xlsx:/definition.xlsx
    ccd-case-management-web:
      ports:
        - 3451:80
    ccd-api-gateway:
      ports:
        - 3453:3453

volumes:
  shared-database-data:
