---
version: '2.1'

services:
    integration-tests:
      build:
        context: .
        args:
          - http_proxy
          - https_proxy
          - no_proxy
      image: docker.artifactory.reform.hmcts.net/cmc/integration-tests:${INTEGRATION_TESTS_VERSION:-latest}
      environment:
        - WEB_DRIVER_HOST=remote-webdriver
        - CITIZEN_APP_URL=https://www-citizen.moneyclaim.reform.hmcts.net:3000
        - LEGAL_APP_URL=https://www-legal.moneyclaim.reform.hmcts.net:4000/legal
        - IDAM_URL=http://idam-api:8080
        - http_proxy
        - https_proxy
        - no_proxy=www-citizen.moneyclaim.reform.hmcts.net,www-legal.moneyclaim.reform.hmcts.net,idam-api,remote-webdriver,authentication-web,claim-store-api
      depends_on:
        remote-webdriver:
          condition: service_started
        citizen-frontend:
          condition: service_started
        legal-frontend:
          condition: service_started
        idam-api:
          condition: service_started
      volumes:
        - ./output:/usr/src/app/output
    remote-webdriver:
      image: docker.artifactory.reform.hmcts.net/selenium/standalone-chrome:3.5.2
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
      mem_limit: 768m
      memswap_limit: 0
    citizen-frontend:
      image: docker.artifactory.reform.hmcts.net/cmc/citizen-frontend:${CITIZEN_FRONTEND_VERSION:-latest}
      environment:
        - NODE_ENV=dockertests
        - IDAM_API_URL=http://idam-api:8080
        - IDAM_AUTHENTICATION_WEB_URL=https://authentication-web:8000
        - IDAM_S2S_AUTH=http://service-auth-provider-api:8080
        - PAY_URL=http://payments-api:8080
        - CLAIM_STORE_URL=http://claim-store-api:4400
        - FEES_URL=http://fees-api:8080
        - PDF_SERVICE_URL=http://pdf-service-api:5500
        - DRAFT_STORE_URL=http://draft-store-api:8800
        - LOG_LEVEL=DEBUG
        - UV_THREADPOOL_SIZE=64
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
        authentication-web:
          condition: service_started
        claim-store-api:
          condition: service_started
        draft-store-api:
          condition: service_started
        fees-api:
          condition: service_started
        payments-api:
          condition: service_started
        pdf-service-api:
          condition: service_started
      networks:
        default:
          aliases:
            - www-citizen.moneyclaim.reform.hmcts.net
    legal-frontend:
      image: docker.artifactory.reform.hmcts.net/cmc/legal-frontend:${LEGAL_FRONTEND_VERSION:-latest}
      environment:
        - NODE_ENV=dockertests
        - IDAM_SECRET_KEY=cmc_it_test_secret_key
        - IDAM_HEALTH_CHECK_URL=http://idam-api:8080/health
        - IDAM_API_URL=http://idam-api:8080
        - IDAM_AUTHENTICATION_WEB_URL=https://authentication-web:8000
        - IDAM_S2S_AUTH=http://service-auth-provider-api:8080
        - FEES_URL=http://fees-api:8080
        - DRAFT_STORE_URL=http://draft-store-api:8800
        - CLAIM_STORE_URL=http://claim-store-api:4400
        - PDF_SERVICE_URL=http://pdf-service-api:5500
        - DOCUMENT_MANAGEMENT_API_GATEWAY_URL=http://document-management-api-gateway-web:8080
        - LOG_LEVEL=DEBUG
        - http_proxy=
        - https_proxy=
        - no_proxy=
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
        authentication-web:
          condition: service_started
        claim-store-api:
          condition: service_started
        draft-store-api:
          condition: service_started
        fees-api:
          condition: service_started
        pdf-service-api:
          condition: service_started
        document-management-api-gateway-web:
          condition: service_started
      networks:
        default:
          aliases:
            - www-legal.moneyclaim.reform.hmcts.net
    authentication-web:
      image: docker.artifactory.reform.hmcts.net/auth/authentication-web:a8c60dd19a4e4518b1145e41a15e99d2d5ff21a8
      environment:
        - IDAM_API_URL=http://idam-api:8080
        - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CMC_LEGAL=123456
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        idam-api:
          condition: service_started
    idam-api:
      image: docker.artifactory.reform.hmcts.net/auth/idam-api:e1fe0c3cb8da83e80ccf939a32ee288cbae20c5a
      command: --wait-for-database 60
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - IDAM_SUPERUSER_EMAIL=cmc-int-test@cmc.reform.hmcts.net
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/idam
        - IDAM_TESTING_SUPPORT_ENABLED=true
        - NOTIFY_API_KEY=${GOV_NOTIFY_API_KEY}
        - NOTIFY_CMC_ACTIVATE_USER_TEMPLATE=76aa8695-64e8-4afd-ae13-bc8385302b1f
        - NOTIFY_CMC_SOLICITOR_ACTIVATE_USER_TEMPLATE=76aa8695-64e8-4afd-ae13-bc8385302b1f
        - IDAM_SECRET=cmc_it_test_secret_key
        - NOTIFY=true
        - NOTIFY_CMC_WELCOME_USER_TEMPLATE=fake
        - NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE=fake
        - NOTIFY_SSCS_WELCOME_USER_TEMPLATE=fake
        - NOTIFY_RESET_PASSWORD_TEMPLATE=fake
        - NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE=fake
        - NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE=fake
        - NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE=fake
        - NOTIFY_CCD_ACTIVATE_USER_TEMPLATE=fake
        - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CMC_CITIZEN=123456
        - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CMC_LEGAL=123456
        - http_proxy
        - https_proxy
        - no_proxy
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
    claim-store-api:
      image: docker.artifactory.reform.hmcts.net/cmc/claim-store-api:${CLAIM_STORE_API_VERSION:-latest}
      healthcheck:
        retries: 40
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - CLAIM_STORE_DB_HOST=shared-database
        - CLAIM_STORE_DB_PORT=5432
        - CLAIM_STORE_DB_USERNAME=claimstore
        - CLAIM_STORE_DB_PASSWORD=claimstore
        - IDAM_API_URL=http://idam-api:8080
        - GOV_NOTIFY_API_KEY
        - FRONTEND_BASE_URL=https://www-citizen.moneyclaim.reform.hmcts.net:3000
        - CLAIM_STORE_TEST_SUPPORT_ENABLED=true
        - STAFF_NOTIFICATIONS_SENDER=no-reply@example.com
        - STAFF_NOTIFICATIONS_RECIPIENT=civilmoneyclaims+staff-int-tests@gmail.com
        - SPRING_MAIL_HOST=smtp-server
        - SPRING_MAIL_PORT=1025
        - PDF_SERVICE_URL=http://pdf-service-api:5500
        - DOCUMENT_MANAGEMENT_API_GATEWAY_URL=http://document-management-api-gateway-web:8080
        - ROOT_APPENDER
        - JSON_CONSOLE_PRETTY_PRINT
        - ROOT_LOGGING_LEVEL
        - REFORM_SERVICE_NAME
        - REFORM_TEAM
        - REFORM_ENVIRONMENT
        - http_proxy
        - https_proxy
        - no_proxy=idam-api,pdf-service-api,document-management-api-gateway-web
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
        idam-api:
          condition: service_started
        smtp-server:
          condition: service_started
        pdf-service-api:
          condition: service_started
        document-management-api-gateway-web:
          condition: service_started
    fees-api:
      image: docker.artifactory.reform.hmcts.net/fees-register/fees-api:33328e91ec54cbf4dbc9f52fe56f3712fe20a331
      healthcheck:
        retries: 40
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - AUTH_IDAM_CLIENT_BASEURL=http://idam-api:8080/
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/fee
        - SPRING_DATASOURCE_USERNAME=fee
        - SPRING_DATASOURCE_PASSWORD=fee
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
        idam-api:
          condition: service_started
    draft-store-api:
      image: docker.artifactory.reform.hmcts.net/reform/draft-store-api:${DRAFT_STORE_API_VERSION:-latest}
      healthcheck:
        retries: 40
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - DRAFT_STORE_DB_HOST=shared-database
        - DRAFT_STORE_DB_PASSWORD=draftstore
        - IDAM_URL=http://idam-api:8080
        - S2S_URL=http://service-auth-provider-api:8080
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
    pdf-service-api:
      image: docker.artifactory.reform.hmcts.net/cmc/pdf-service-api
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - ROOT_APPENDER
        - JSON_CONSOLE_PRETTY_PRINT
        - ROOT_LOGGING_LEVEL
        - REFORM_SERVICE_NAME
        - REFORM_TEAM
        - REFORM_ENVIRONMENT
      healthcheck:
        retries: 40
      mem_limit: 512m
      memswap_limit: 0
    service-auth-provider-api:
      image: docker.artifactory.reform.hmcts.net/auth/service-auth-provider-api:47e18b53aad48ae8124744041988565e07dfed50
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - auth.provider.service.server.jwtKey=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
        - auth.provider.service.server.microserviceKeys.cmc=AAAAAAAAAAAAAAAA
        - auth.provider.service.server.microserviceKeys.cmc_legal_frontend=AAAAAAAAAAAAAAAA
        - auth.provider.service.server.microserviceKeys.em_gw=AAAAAAAAAAAAAAAA
        - auth.provider.service.testing-support.enabled=true
      mem_limit: 512m
      memswap_limit: 0
    payments-api:
      image: docker.artifactory.reform.hmcts.net/common-components/payments-api:81c947e7ef478338d4aff8bd8536dd81d83e2104
      healthcheck:
        retries: 40
      command: --wait-for-database 60
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/payment
        - auth.provider.service.client.baseUrl=http://service-auth-provider-api:8080/
        - auth.idam.client.baseUrl=http://idam-api:8080/
        - GOV_PAY_AUTH_KEY_CMC
        - http_proxy
        - https_proxy
        - no_proxy=idam-api,service-auth-provider-api,$no_proxy
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
    shared-database:
      image: postgres:9.6-alpine
      volumes:
        - ./docker/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      healthcheck:
        test: psql -c 'select 1' -d postgres -U postgres
        retries: 40
      mem_limit: 160m
      memswap_limit: 0
    smtp-server:
      image: mailhog/mailhog
      mem_limit: 32m
      memswap_limit: 0
    document-management-api-gateway-web:
      image: docker.artifactory.reform.hmcts.net/evidence/em-api-gateway-web:aec3b03a1f824881d4f09597ce29851b2be5b5cb
      environment:
        - NODE_ENV=development
        - PORT=8080
        - EM_API_URL=http://document-management-api:8080
        - IDAM_BASE_URL=http://idam-api:8080
        - IDAM_S2S_URL=http://service-auth-provider-api:8080
        - IDAM_SERVICE_KEY=AAAAAAAAAAAAAAAA
        - IDAM_SERVICE_NAME=em_gw
        - CORS_ORIGIN_METHODS=GET,POST,PUT,DELETE,OPTIONS
        - CORS_ORIGIN_WHITELIST=http://document-management-api:8080
        #      logging env vars
        - ROOT_APPENDER
        - REFORM_SERVICE_TYPE=node
        - REFORM_SERVICE_NAME=document-management-api-gateway-web
        - REFORM_TEAM=cc
        - REFORM_ENVIRONMENT=docker
        - XFWD=true
        - LOG_LEVEL=DEBUG
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        document-management-api:
          condition: service_started
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
    document-management-api:
      image: docker.artifactory.reform.hmcts.net/evidence/document-management-store:1f97d3d40f70dbb241a891d55dcc3b7531da7127
      command: --wait-for-database 60
      environment:
        - SERVER_PORT=8080
        - JAVA_OPTS=-Xms8m -Xmx256m
        - IDAM_SUPERUSER_EMAIL
        - IDAM_SECRET_KEY
        - GOV_NOTIFY_API_KEY
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/evidence
        - SPRING_DATASOURCE_USERNAME=evidence
        - SPRING_DATASOURCE_PASSWORD=evidence
        - SPRING_PROFILES_ACTIVE=dev
        - IDAM_TESTING_SUPPORT_ENABLED=true
        - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
        - IDAM_CLIENT_URL=http://idam-api:8080
        - PROVIDER_SERVICE_CLIENT_URL=http://service-auth-provider-api:8080
        - http_proxy=
        - https_proxy=
        - no_proxy=
  #      logging env vars
        - ROOT_APPENDER
        - REFORM_SERVICE_TYPE=java
        - REFORM_SERVICE_NAME=document-management-api
        - REFORM_TEAM=cc
        - REFORM_ENVIRONMENT=docker
        - LOGGING_LEVEL_ROOT=DEBUG
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
