---
version: '2.1'

services:
    integration-tests:
      build:
        context: .
        args:
          - http_proxy
          - https_proxy
          - no_proxy
      image: docker.artifactory.reform.hmcts.net/cmc/integration-tests:${INTEGRATION_TESTS_VERSION:-latest}
      environment:
        - WEB_DRIVER_HOST=remote-webdriver
        - CITIZEN_APP_URL=https://www-citizen.moneyclaim.reform.hmcts.net:3000
        - LEGAL_APP_URL=https://www-legal.moneyclaim.reform.hmcts.net:4000/legal
        - IDAM_URL=http://idam-api:8080
        - CLAIM_STORE_URL=http://claim-store-api:4400
        - http_proxy
        - https_proxy
        - no_proxy=www-citizen.moneyclaim.reform.hmcts.net,www-legal.moneyclaim.reform.hmcts.net,idam-api,remote-webdriver,authentication-web,claim-store-api
      depends_on:
        remote-webdriver:
          condition: service_started
        citizen-frontend:
          condition: service_started
        legal-frontend:
          condition: service_started
        idam-api:
          condition: service_started
      volumes:
        - ./output:/usr/src/app/output
    remote-webdriver:
      image: docker.artifactory.reform.hmcts.net/selenium/standalone-chrome:3.8.1
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
      mem_limit: 768m
      memswap_limit: 0
    citizen-frontend:
      image: docker.artifactory.reform.hmcts.net/cmc/citizen-frontend:${CITIZEN_FRONTEND_VERSION:-latest}
      environment:
        - NODE_ENV=dockertests
        - IDAM_API_URL=http://idam-api:8080
        - IDAM_AUTHENTICATION_WEB_URL=https://authentication-web:8000
        - IDAM_S2S_AUTH=http://service-auth-provider-api:8080
        - PAY_URL=http://payments-api:8080
        - CLAIM_STORE_URL=http://claim-store-api:4400
        - FEES_URL=http://fees-api:8080
        - PDF_SERVICE_URL=http://pdf-service-api:5500
        - DRAFT_STORE_URL=http://draft-store-api:8800
        - LOG_LEVEL
        - UV_THREADPOOL_SIZE=64
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
        authentication-web:
          condition: service_started
        claim-store-api:
          condition: service_started
        draft-store-api:
          condition: service_started
        fees-api:
          condition: service_started
        payments-api:
          condition: service_started
        pdf-service-api:
          condition: service_started
      networks:
        default:
          aliases:
            - www-citizen.moneyclaim.reform.hmcts.net
    legal-frontend:
      image: docker.artifactory.reform.hmcts.net/cmc/legal-frontend:${LEGAL_FRONTEND_VERSION:-latest}
      environment:
        - NODE_ENV=dockertests
        - IDAM_SECRET_KEY=cmc_it_test_secret_key
        - IDAM_HEALTH_CHECK_URL=http://idam-api:8080/health
        - IDAM_API_URL=http://idam-api:8080
        - IDAM_AUTHENTICATION_WEB_URL=https://authentication-web:8000
        - IDAM_S2S_AUTH=http://service-auth-provider-api:8080
        - FEES_URL=http://fees-api:8080
        - DRAFT_STORE_URL=http://draft-store-api:8800
        - CLAIM_STORE_URL=http://claim-store-api:4400
        - PDF_SERVICE_URL=http://pdf-service-api:5500
        - DOCUMENT_MANAGEMENT_API_GATEWAY_URL=http://document-management-api-gateway-web:8080
        - LOG_LEVEL
        - http_proxy=
        - https_proxy=
        - no_proxy=
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
        authentication-web:
          condition: service_started
        claim-store-api:
          condition: service_started
        draft-store-api:
          condition: service_started
        fees-api:
          condition: service_started
        pdf-service-api:
          condition: service_started
        document-management-api-gateway-web:
          condition: service_started
      networks:
        default:
          aliases:
            - www-legal.moneyclaim.reform.hmcts.net
    authentication-web:
      image: docker.artifactory.reform.hmcts.net/auth/authentication-web:a8c60dd19a4e4518b1145e41a15e99d2d5ff21a8
      environment:
        - IDAM_API_URL=http://idam-api:8080
        - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CMC_LEGAL=123456
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        idam-api:
          condition: service_started
    idam-api:
      image: docker.artifactory.reform.hmcts.net/auth/idam-api:ea84d227d19ae816686407bb49e747f779def5e4
      command: --wait-for-database 60
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - IDAM_SUPERUSER_EMAIL=cmc-int-test@cmc.reform.hmcts.net
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/idam
        - IDAM_TESTING_SUPPORT_ENABLED=true
        - NOTIFY_API_KEY=${GOV_NOTIFY_API_KEY}
        - NOTIFY_CMC_ACTIVATE_USER_TEMPLATE=76aa8695-64e8-4afd-ae13-bc8385302b1f
        - NOTIFY_CMC_SOLICITOR_ACTIVATE_USER_TEMPLATE=76aa8695-64e8-4afd-ae13-bc8385302b1f
        - IDAM_SECRET=cmc_it_test_secret_key
        - NOTIFY=true
        - NOTIFY_CMC_WELCOME_USER_TEMPLATE=fake
        - NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE=fake
        - NOTIFY_SSCS_WELCOME_USER_TEMPLATE=fake
        - NOTIFY_RESET_PASSWORD_TEMPLATE=fake
        - NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE=fake
        - NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE=fake
        - NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE=fake
        - NOTIFY_CCD_ACTIVATE_USER_TEMPLATE=fake
        - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CMC_CITIZEN=123456
        - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CMC_LEGAL=123456
        - http_proxy
        - https_proxy
        - no_proxy
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
    claim-store-api:
      image: docker.artifactory.reform.hmcts.net/cmc/claim-store-api:${CLAIM_STORE_API_VERSION:-latest}
      healthcheck:
        retries: 40
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - CLAIM_STORE_DB_HOST=shared-database
        - CLAIM_STORE_DB_PORT=5432
        - CLAIM_STORE_DB_USERNAME=claimstore
        - CLAIM_STORE_DB_PASSWORD=claimstore
        - IDAM_API_URL=http://idam-api:8080
        - IDAM_S2S_AUTH_URL=http://service-auth-provider-api:8080
        - GOV_NOTIFY_API_KEY
        - FRONTEND_BASE_URL=https://www-citizen.moneyclaim.reform.hmcts.net:3000
        - CLAIM_STORE_TEST_SUPPORT_ENABLED=true
        - STAFF_NOTIFICATIONS_SENDER=no-reply@example.com
        - STAFF_NOTIFICATIONS_RECIPIENT=civilmoneyclaims+staff-int-tests@gmail.com
        - SPRING_MAIL_HOST=smtp-server
        - SPRING_MAIL_PORT=1025
        - PDF_SERVICE_URL=http://pdf-service-api:5500
        - DOCUMENT_MANAGEMENT_API_GATEWAY_URL=http://document-management-api-gateway-web:8080
        - CORE_CASE_DATA_API_URL=http://ccd-data-store-api:4452
        - FEATURE_TOGGLE_CORE_CASE_DATA=true
        - ROOT_APPENDER
        - JSON_CONSOLE_PRETTY_PRINT
        - ROOT_LOGGING_LEVEL
        - REFORM_SERVICE_NAME=claim-store
        - REFORM_TEAM
        - REFORM_ENVIRONMENT
        - http_proxy
        - https_proxy
        - no_proxy=idam-api,service-auth-provider-api,pdf-service-api,document-management-api-gateway-web,ccd-data-store-api
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
        idam-api:
          condition: service_started
        smtp-server:
          condition: service_started
        pdf-service-api:
          condition: service_started
        document-management-api-gateway-web:
          condition: service_started
        ccd-user-profile-api:
          condition: service_started
        ccd-definition-store-api:
          condition: service_started
        ccd-data-store-api:
          condition: service_started


    fees-api:
      image: docker.artifactory.reform.hmcts.net/fees-register/fees-api:33328e91ec54cbf4dbc9f52fe56f3712fe20a331
      healthcheck:
        retries: 40
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - AUTH_IDAM_CLIENT_BASEURL=http://idam-api:8080/
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/fee
        - SPRING_DATASOURCE_USERNAME=fee
        - SPRING_DATASOURCE_PASSWORD=fee
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
        idam-api:
          condition: service_started
    draft-store-api:
      image: docker.artifactory.reform.hmcts.net/reform/draft-store-api:${DRAFT_STORE_API_VERSION:-latest}
      healthcheck:
        retries: 40
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - DRAFT_STORE_DB_HOST=shared-database
        - DRAFT_STORE_DB_PASSWORD=draftstore
        - IDAM_URL=http://idam-api:8080
        - S2S_URL=http://service-auth-provider-api:8080
        - ROOT_APPENDER
        - JSON_CONSOLE_PRETTY_PRINT
        - ROOT_LOGGING_LEVEL
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
    pdf-service-api:
      image: docker.artifactory.reform.hmcts.net/reform/pdf-service-api
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - S2S_URL=http://service-auth-provider-api:8080
        - ROOT_APPENDER
        - JSON_CONSOLE_PRETTY_PRINT
        - ROOT_LOGGING_LEVEL
        - REFORM_SERVICE_NAME=pdf-service
        - REFORM_TEAM
        - REFORM_ENVIRONMENT
      healthcheck:
        retries: 40
      mem_limit: 512m
      memswap_limit: 0
    service-auth-provider-api:
      image: docker.artifactory.reform.hmcts.net/auth/service-auth-provider-api:47e18b53aad48ae8124744041988565e07dfed50
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - auth.provider.service.server.jwtKey=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
        - auth.provider.service.server.microserviceKeys.cmc=AAAAAAAAAAAAAAAA
        - auth.provider.service.server.microserviceKeys.cmc_legal_frontend=AAAAAAAAAAAAAAAA
        - auth.provider.service.server.microserviceKeys.cmc_claim_store=AAAAAAAAAAAAAAAA
        - auth.provider.service.server.microserviceKeys.em_gw=AAAAAAAAAAAAAAAA
        - auth.provider.service.server.microserviceKeys.ccd_data=AAAAAAAAAAAAAAAA
        - auth.provider.service.server.microserviceKeys.ccd_definition=AAAAAAAAAAAAAAAA
        - auth.provider.service.testing-support.enabled=true
      mem_limit: 512m
      memswap_limit: 0
    payments-api:
      image: docker.artifactory.reform.hmcts.net/common-components/payments-api:3672f2cb0658ea7fcbbc9039ae24eb0b66e9528f
      healthcheck:
        retries: 40
      command: --wait-for-database 60
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/payment
        - AUTH_PROVIDER_SERVICE_CLIENT_BASEURL=http://service-auth-provider-api:8080/
        - AUTH_IDAM_CLIENT_BASEURL=http://idam-api:8080/
        - GOV_PAY_AUTH_KEY_CMC
        - http_proxy
        - https_proxy
        - no_proxy=idam-api,service-auth-provider-api,$no_proxy
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
    shared-database:
      image: postgres:9.6-alpine
      volumes:
        - ./docker/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      healthcheck:
        test: psql -c 'select 1' -d postgres -U postgres
        retries: 40
      mem_limit: 160m
      memswap_limit: 0
    smtp-server:
      image: mailhog/mailhog
      mem_limit: 32m
      memswap_limit: 0
    document-management-api-gateway-web:
      image: docker.artifactory.reform.hmcts.net/evidence/document-management-store-api-gateway-web:d8ed69bca12faad8906dd1eec5800b0134307901
      environment:
        - NODE_ENV=development
        - PORT=8080
        - EM_API_URL=http://document-management-api:8080
        - IDAM_BASE_URL=http://idam-api:8080
        - IDAM_S2S_URL=http://service-auth-provider-api:8080
        - IDAM_SERVICE_KEY=AAAAAAAAAAAAAAAA
        - IDAM_SERVICE_NAME=em_gw
        - CORS_ORIGIN_METHODS=GET,POST,PUT,DELETE,OPTIONS
        - CORS_ORIGIN_WHITELIST=http://document-management-api:8080
        #      logging env vars
        - ROOT_APPENDER
        - REFORM_SERVICE_TYPE=node
        - REFORM_SERVICE_NAME=document-management-api-gateway-web
        - REFORM_TEAM=cc
        - REFORM_ENVIRONMENT=docker
        - XFWD=true
        - LOG_LEVEL
      mem_limit: 256m
      memswap_limit: 0
      depends_on:
        document-management-api:
          condition: service_started
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
    document-management-api:
      image: docker.artifactory.reform.hmcts.net/evidence/document-management-store:1f97d3d40f70dbb241a891d55dcc3b7531da7127
      command: --wait-for-database 60
      environment:
        - SERVER_PORT=8080
        - JAVA_OPTS=-Xms8m -Xmx256m
        - IDAM_SUPERUSER_EMAIL
        - IDAM_SECRET_KEY
        - GOV_NOTIFY_API_KEY
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/evidence
        - SPRING_DATASOURCE_USERNAME=evidence
        - SPRING_DATASOURCE_PASSWORD=evidence
        - SPRING_PROFILES_ACTIVE=dev
        - IDAM_TESTING_SUPPORT_ENABLED=true
        - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM
        - IDAM_CLIENT_URL=http://idam-api:8080
        - PROVIDER_SERVICE_CLIENT_URL=http://service-auth-provider-api:8080
        - http_proxy=
        - https_proxy=
        - no_proxy=
  #      logging env vars
        - ROOT_APPENDER
        - REFORM_SERVICE_TYPE=java
        - REFORM_SERVICE_NAME=document-management-api
        - REFORM_TEAM=cc
        - REFORM_ENVIRONMENT=docker
        - LOGGING_LEVEL_ROOT
        - DM_MULTIPART_WHITELIST=text/plain,text/csv,image/gif,image/tiff,image/jpeg,image/png,image/webp,image/svg+xml,image/bmp,application/pdf,application/rtf,application/msword,application/vnd.ms-powerpoint,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.oasis.opendocument.text,application/vnd.oasis.opendocument.spreadsheet,application/vnd.oasis.opendocument.presentation,application/xml,audio/wav,audio/midi,audio/mpeg,audio/webm,audio/ogg,video/ogg,audio/3gpp,video/3gpp,audio/3gpp2,video/3gpp2,audio/x-wav,audio/wav,video/webm,video/mpeg
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
        idam-api:
          condition: service_started
        service-auth-provider-api:
          condition: service_started
    ccd-user-profile-api:
        image: docker.artifactory.reform.hmcts.net/ccd/ccd-user-profile-api:ae7bfdf86fc24fc0f44b5df11e7890f3bef1feff
        environment:
          - JAVA_OPTS=-Xms8m -Xmx256m
          - USER_PROFILE_DB_HOST=shared-database
          - USER_PROFILE_DB_PORT=5432
          - USER_PROFILE_DB_USERNAME=ccd_user_profile
          - USER_PROFILE_DB_PASSWORD=ccd_user_profile
          - USER_PROFILE_S2S_AUTHORISED_SERVICES=ccd_data,ccd_definition
          - IDAM_S2S_URL=http://service-auth-provider-api:8080
          - REFORM_SERVICE_NAME=ccd-user-profile-api
          - REFORM_TEAM=ccd
          - REFORM_ENVIRONMENT=local
        mem_limit: 512m
        memswap_limit: 0
        depends_on:
          shared-database:
            condition: service_healthy

    ccd-definition-store-api:
      image: docker.artifactory.reform.hmcts.net/ccd/ccd-definition-store-api:7974d4a24d8453f8c1ab6e99a461a8f2e2106370
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - DEFINITION_STORE_DB_HOST=shared-database
        - DEFINITION_STORE_DB_PORT=5432
        - DEFINITION_STORE_DB_USERNAME=ccd_definition_store
        - DEFINITION_STORE_DB_PASSWORD=ccd_definition_store
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/ccd_definition_store
        - DEFINITION_STORE_IDAM_KEY=AAAAAAAAAAAAAAAA
        - DEFINITION_STORE_S2S_AUTHORISED_SERVICES=ccd_data,cmc_claim_store
        - USER_PROFILE_HOST=http://ccd-user-profile-api:4453
        - IDAM_USER_URL=http://idam-api:8080
        - IDAM_S2S_URL=http://service-auth-provider-api:8080
        - REFORM_SERVICE_NAME=ccd-definition-store-api
        - REFORM_TEAM=ccd
        - REFORM_ENVIRONMENT=local
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy

    ccd-data-store-api:
      image: docker.artifactory.reform.hmcts.net/ccd/ccd-data-store-api:9210c225611480022214e8f6fa968d1c2e4367c0
      environment:
        - JAVA_OPTS=-Xms8m -Xmx256m
        - DATA_STORE_DB_HOST=shared-database
        - DATA_STORE_DB_PORT=5432
        - DATA_STORE_DB_USERNAME=ccd_data_store
        - DATA_STORE_DB_PASSWORD=ccd_data_store
        - DATA_STORE_IDAM_KEY=AAAAAAAAAAAAAAAA
        - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/ccd_data_store?stringtype=unspecified
        - DATA_STORE_TOKEN_SECRET=sdsadahjsadhgaskjhdhasghgkjasd
        - DATA_STORE_S2S_AUTHORISED_SERVICES=cmc_claim_store
        - DEFINITION_STORE_HOST=http://ccd-definition-store-api:4451
        - USER_PROFILE_HOST=http://ccd-user-profile-api:4453
        - IDAM_USER_URL=http://idam-api:8080
        - IDAM_S2S_URL=http://service-auth-provider-api:8080
        - REFORM_SERVICE_NAME=ccd-data-store-api
        - REFORM_TEAM=ccd
        - REFORM_ENVIRONMENT=local
      mem_limit: 512m
      memswap_limit: 0
      depends_on:
        shared-database:
          condition: service_healthy
    ccd-importer:
      build:
        context: docker/ccd-definition-import
      image: docker.artifactory.reform.hmcts.net/cmc/ccd-importer:${CCD_IMPORTER_VERSION:-latest}
      environment:
        WAIT_HOSTS: ccd-user-profile-api:4453, ccd-definition-store-api:4451, service-auth-provider-api:8080, idam-api:8080
        WAIT_HOSTS_TIMEOUT: 300
