const verifyPageData = require('../../../data/legal-test-data').verifyPageData

Feature('Defendants Enter details of claim')

Scenario('I can fill in Claimant organization, more Defendant details and update their details @legal', function * (I, legalUserSteps, legalDefendantSteps) {
  const userEmail = yield I.createSolicitorUser()
  legalUserSteps.loginAndStartClaim(userEmail)
  legalUserSteps.enterClaimantServiceDetails()
  legalUserSteps.enterClaimantTypeOrganisation()
  I.see('Claimant: ' + verifyPageData.claimantOrganization)
  legalUserSteps.enterClaimantAddress()
  legalUserSteps.noAdditionalClaimant()
  legalDefendantSteps.enterDefendantTypeOrganisation()
  I.see('Defendant: ' + verifyPageData.defendantOrganization)
  legalDefendantSteps.enterDefendantAddress()
  legalDefendantSteps.enterDefendantRepsCompanyName()
  I.see("Defendant's legal representative: Defendant Rep Ltd")
  legalDefendantSteps.enterDefendantRepsAddress()
  legalDefendantSteps.enterAnotherDefendant()
  legalDefendantSteps.enterAnotherDefendantTypeIndividual()
  I.see('Defendant 2: Mrs Orange')
  legalDefendantSteps.enterDefendantAddress()
  legalDefendantSteps.noDefendantCompanyName()
  legalDefendantSteps.enterServiceAddress()
  legalDefendantSteps.enterAnotherDefendant()
  legalDefendantSteps.enterAnotherDefendantTypeOrganisation()
  I.see('Defendant 3: Ghi corporation')
  legalDefendantSteps.enterDefendantAddress()
  legalDefendantSteps.enterDefendantRepsCompanyName()
  I.see("Defendant 3's legal representative: Defendant Rep Ltd")
  legalDefendantSteps.enterDefendantRepsAddress()
  legalDefendantSteps.verifyAndChangeDefendantDetails()
})

Scenario('I can fill in Claimant individual and Defendant individual details @legal', function * (I, legalUserSteps, legalDefendantSteps) {
  const userEmail = yield I.createSolicitorUser()
  legalUserSteps.loginAndStartClaim(userEmail)
  legalUserSteps.enterClaimantServiceDetails()
  legalUserSteps.enterClaimantTypeIndividual()
  I.see('Claimant: Mr Benugo')
  legalUserSteps.enterClaimantAddress()
  legalUserSteps.noAdditionalClaimant()
  legalDefendantSteps.enterDefendantTypeIndividual()
  I.see('Defendant: Mr Pret')
  legalDefendantSteps.enterDefendantAddress()
  legalDefendantSteps.noDefendantCompanyName()
  legalDefendantSteps.defendantAddressAsServiceAddress()
  legalDefendantSteps.noAnotherDefendant()
})

Scenario('Check Error Messages in Enter your defendant address Page @legal', function * (I, legalUserSteps, legalDefendantType, legalDefendantSteps, legalDefendantAddress) {
  const userEmail = yield I.createSolicitorUser()
  legalUserSteps.loginAndStartClaim(userEmail)
  legalDefendantType.open()
  legalDefendantSteps.enterDefendantTypeOrganisation()
  I.see('Defendant: ' + verifyPageData.defendantOrganization)
  legalDefendantAddress.checkForAddressLineLength()
  legalDefendantAddress.checkForPostCodeLengthMessage()
})

Scenario('Check Error Messages in Enter your defendant representative address Page @legal', function * (I, legalUserSteps, legalDefendantType, legalDefendantSteps, legalDefendantRepresentativeAddress) {
  const userEmail = yield I.createSolicitorUser()
  legalUserSteps.loginAndStartClaim(userEmail)
  legalDefendantType.open()
  legalDefendantSteps.enterDefendantTypeOrganisation()
  legalDefendantSteps.enterDefendantAddress()
  legalDefendantSteps.enterDefendantRepsCompanyName()
  legalDefendantRepresentativeAddress.checkForAddressLineLength()
  legalDefendantRepresentativeAddress.checkForPostCodeLengthMessage()
})

Scenario('Check Error Messages on defendant service address Page @legal', function * (I, legalUserSteps, legalDefendantType, legalDefendantSteps, legalDefendantAddServiceAddress) {
  const userEmail = yield I.createSolicitorUser()
  legalUserSteps.loginAndStartClaim(userEmail)
  legalDefendantType.open()
  legalDefendantSteps.enterDefendantTypeOrganisation()
  legalDefendantSteps.enterDefendantAddress()
  legalDefendantSteps.noDefendantCompanyName()
  legalDefendantAddServiceAddress.checkForPostCodeLengthMessage()
  legalDefendantAddServiceAddress.checkForAddressLineLength()
})
